- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: security
  color: 8b0000
  description: Security-related work
- name: ops
  color: 0e8a16
  description: Operations, automation, CI/CD
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
