import { useState } from 'react'

export default function LoginFIDO2({ onSuccess, onError }) {
  const [loading, setLoading] = useState(false)
  const [registering, setRegistering] = useState(false)

  const handleRegister = async () => {
    setRegistering(true)
    setLoading(true)

    try {
      // Check if WebAuthn is supported
      if (!window.PublicKeyCredential) {
        throw new Error('WebAuthn is not supported in this browser')
      }

      // Create credential options
      const publicKeyCredentialCreationOptions = {
        challenge: new Uint8Array(32), // In production, get from server
        rp: {
          name: 'EchoForge',
          id: window.location.hostname,
        },
        user: {
          id: new Uint8Array(16),
          name: 'user@echoforge.app',
          displayName: 'EchoForge User',
        },
        pubKeyCredParams: [
          { alg: -7, type: 'public-key' }, // ES256
          { alg: -257, type: 'public-key' }, // RS256
        ],
        authenticatorSelection: {
          authenticatorAttachment: 'platform',
          userVerification: 'required',
        },
        timeout: 60000,
        attestation: 'direct',
      }

      // Create credentials
      const credential = await navigator.credentials.create({
        publicKey: publicKeyCredentialCreationOptions,
      })

      console.log('Registration successful', credential)
      alert('Registration successful! You can now login.')
      setRegistering(false)
    } catch (error) {
      console.error('Registration failed', error)
      onError(error)
      alert('Registration failed: ' + error.message)
    } finally {
      setLoading(false)
    }
  }

  const handleLogin = async () => {
    setLoading(true)

    try {
      // Check if WebAuthn is supported
      if (!window.PublicKeyCredential) {
        throw new Error('WebAuthn is not supported in this browser')
      }

      // Get credential options
      const publicKeyCredentialRequestOptions = {
        challenge: new Uint8Array(32), // In production, get from server
        timeout: 60000,
        userVerification: 'required',
      }

      // Get credentials
      const credential = await navigator.credentials.get({
        publicKey: publicKeyCredentialRequestOptions,
      })

      if (!credential) {
        throw new Error('Authentication failed')
      }

      // Store auth status (in production, validate with server)
      sessionStorage.setItem('authenticated', 'true')
      
      console.log('Login successful', credential)
      onSuccess(credential)
    } catch (error) {
      console.error('Login failed', error)
      onError(error)
      alert('Login failed: ' + error.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fido2-login">
      <div className="fido2-buttons">
        <button 
          onClick={handleLogin}
          disabled={loading}
          className="button primary"
        >
          {loading && !registering ? 'Authenticating...' : '🔐 Login with Biometrics'}
        </button>

        <button 
          onClick={handleRegister}
          disabled={loading}
          className="button secondary"
        >
          {loading && registering ? 'Registering...' : '📝 Register New Device'}
        </button>
      </div>

      <div className="fido2-info">
        <p className="info-text">
          <strong>Note:</strong> This is a demo implementation. In production:
        </p>
        <ul>
          <li>Challenges should be generated by the server</li>
          <li>Credentials should be validated server-side</li>
          <li>User IDs should be unique and persistent</li>
        </ul>
      </div>
    </div>
  )
}
